### **Scrape the Data from the Web**

In [1]:
#for writing to excel(xlsx) we will be needing XlsxWriter, please install it first if you don't have it!
try:
  import XlsxWriter
except ModuleNotFoundError:
  print("XlsxWriter is not installed!!")
  get_ipython().system("pip install XlsxWriter")

#to scrape a table from a webpage
from urllib.parse import urlparse,urlsplit
import requests
import pandas as pd
import os


urls=["https://www.openacessjournal.com/impact-factor-list-journals",
      "https://www.openacessjournal.com/indexed-journals-list",
      "https://www.openacessjournal.com/blog/scopus-indexed-journals/"
      ]


print(len(urls),"Urls Found")

#convert the sheetname- remove _ and - , put title case and remove spaces
def modify_name(my_str):
  replaced=my_str.replace("_", " ").replace("-", " ")
  return replaced.title().replace(" ","")


#get all tables from a url
def get_dataframes(url):
  html = requests.get(url).content
  df_list = pd.read_html(html)
  #print(len(df_list)," Dataframes Returned")
  return df_list

#if df is too small then don't add it
def filter_dfs(dfs_list,min_rows=10):
  new_dfs_list=[]
  for each_df in dfs_list:
    if(len(each_df)>min_rows):
      new_dfs_list.append(each_df)
  return new_dfs_list

#to avoid InvalidWorksheetName: Excel worksheet name 'StatesAndUnionTerritoriesOfIndia1' must be <= 31 chars.
def crop_name(name,thres=29):
  if len(name)<thres:
    return name
  else:
    return name[:thres]

#to get first n elements from list only
def crop_list(lst,thres=29):
  if len(lst)<thres:
    return lst
  else:
    return lst[:thres]

#converts urls to dataframes to excel sheets
#get_max= get the maximum number of tables from each url
#min_rows= the minimum number of rows in each table to save it to the excel sheet
#crop_name_thres= some excel sheets can get quite huge sheet names which blows up the code
#so crop the sheet name for the better purpose

def urls_to_excel(urls,excel_path=None,get_max=10,min_rows=0,crop_name_thres=29):
  excel_path=os.path.join(os.getcwd(),"Excel_Multiple_Sheets_Output.xlsx") if excel_path==None else excel_path
  writer = pd.ExcelWriter(excel_path, engine='xlsxwriter')
  i=0
  for url in urls:
    parsed=urlsplit(url)
    sheet_name=parsed.path.split('/')[-1]
    mod_sheet_name=crop_name(modify_name(sheet_name),thres=crop_name_thres)

    dfs_list=get_dataframes(url)
    filtered_dfs_list=filter_dfs(dfs_list,min_rows=min_rows)
    filtered_dfs_list=crop_list(filtered_dfs_list,thres=get_max)
    for each_df in filtered_dfs_list:
      print("Parsing Excel Sheet "," : ",str(i)+mod_sheet_name)
      i+=1
      each_df.to_excel(writer, sheet_name=str(i)+mod_sheet_name, index=True)
  writer.save()
urls_to_excel(urls,get_max=100,min_rows=1)

XlsxWriter is not installed!!
     |████████████████████████████████| 153kB 3.9MB/s 
3 Urls Found
Parsing Excel Sheet   :  0ImpactFactorListJournals
Parsing Excel Sheet   :  1IndexedJournalsList
Parsing Excel Sheet   :  2
Parsing Excel Sheet   :  3
Parsing Excel Sheet   :  4
Parsing Excel Sheet   :  5
Parsing Excel Sheet   :  6
Parsing Excel Sheet   :  7
Parsing Excel Sheet   :  8
Parsing Excel Sheet   :  9


### Clean the Data Locally

In [2]:
!git clone https://github.com/khanfarhan10/OpenAccessJournalsData.git

Cloning into 'OpenAccessJournalsData'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 15 (delta 2), reused 7 (delta 0), pack-reused 0
Unpacking objects: 100% (15/15), done.


In [3]:
import os
import pandas as pd
import numpy as np

DATA_FOLDER = "/content/OpenAccessJournalsData/Data"

OAJournals = os.path.join(DATA_FOLDER,"Open_Access_Journals.xlsx")
SCIJournals = os.path.join(DATA_FOLDER,"Scopus_Indexed_Journals.xlsx")

In [4]:
# Read all sheets in your File
dfOA = pd.read_excel(OAJournals, sheet_name=None)
    
# Prints all the sheets name in an ordered dictionary
print(dfOA.keys())

dict_keys(['ImpactFactorListJournals', 'IndexedJournalsList'])


In [5]:
Sheets = list(dfOA.keys())
for sheet_name in Sheets:
  print("Sheet Name :",sheet_name)
  df = dfOA[sheet_name]
  print(df.head())

Sheet Name : ImpactFactorListJournals
   No                            Journals title Impact factor list
0   1                       Academic Pediatrics       2.007 (2020)
1   2                         Acta Orthopaedica       3.217 (2020)
2   3              Advances in Medical Sciences       2.080 (2020)
3   4                 Aesthetic Surgery Journal        3.48 (2020)
4   5  American Journal of Clinical Dermatology       3.840 (2020)
Sheet Name : IndexedJournalsList
   No                          Indexed Journals title
0   1                    Journal of Diabetes Research
1   2                    Journal of Materials Science
2   3                                      The Lancet
3   4              Indian Journal of Medical Research
4   5  Australasian Journal of Educational Technology


In [6]:
if1 = list(dfOA[Sheets[0]]["Impact factor list"])

def cleaner(x):
  try: 
    ans = float(x.split(" ")[0])
  except:
    ans=-1
  return ans

clean_if1 = list(map(lambda x: cleaner(x), if1))

In [7]:
Journals = list(dfOA[Sheets[0]]["Journals title"]) + list(dfOA[Sheets[1]]["Indexed Journals title"])
SourceOA = [Sheets[0]]*len(dfOA[Sheets[0]]["Journals title"]) + [Sheets[1]]*len(dfOA[Sheets[1]]["Indexed Journals title"])
IF2020 = clean_if1 + [-1]*len(dfOA[Sheets[1]]["Indexed Journals title"])

In [8]:
df = pd.DataFrame.from_dict({"JournalName" : Journals,
                            "ImpactFactor2020" : IF2020 ,
                            "Source" : SourceOA    }         
                            )
df["Type"] = "OpenAccess"
# df = pd.DataFrame(columns=["JournalName","ImpactFactor","Source"])
df.head()

JournalName  ...        Type
0                       Academic Pediatrics  ...  OpenAccess
1                         Acta Orthopaedica  ...  OpenAccess
2              Advances in Medical Sciences  ...  OpenAccess
3                 Aesthetic Surgery Journal  ...  OpenAccess
4  American Journal of Clinical Dermatology  ...  OpenAccess

[5 rows x 4 columns]

In [9]:
# Read all sheets in your File
dfSCI = pd.read_excel(SCIJournals, sheet_name=None)
    
# Prints all the sheets name in an ordered dictionary
print(dfSCI.keys())

dict_keys(['SCI_Journals_2020', 'ArtsAndHumanities', 'BusinessManagementAccounting', 'ComputerScience', 'TopCiteScore', 'TopCited', 'TopCitedOpenAccess', 'TopCitations'])


In [10]:
Sheets = list(dfSCI.keys())
All_SCI = []
Source = []
for sheet_name in Sheets:
  each_df = dfSCI[sheet_name]
  current_journals = list(each_df["JournalName"])
  All_SCI = All_SCI + current_journals
  Source = Source+ [sheet_name] * len(current_journals)

In [11]:
len(All_SCI)

702

In [12]:
df2 = pd.DataFrame.from_dict({"JournalName" : All_SCI,
                            "ImpactFactor2020" : [-1]*len(All_SCI) ,
                            "Source" : Source     }         
                            )
df2["Type"] = "SCI"

In [13]:
df2.head()

JournalName  ...  Type
0                                          3 Biotech  ...   SCI
1              3L: Language, Linguistics, Literature  ...   SCI
2                                       AACL Bioflux  ...   SCI
3  AAPP Atti della Accademia Peloritana dei Peric...  ...   SCI
4                                  AAPS PharmSciTech  ...   SCI

[5 rows x 4 columns]

In [14]:
df.head()

JournalName  ...        Type
0                       Academic Pediatrics  ...  OpenAccess
1                         Acta Orthopaedica  ...  OpenAccess
2              Advances in Medical Sciences  ...  OpenAccess
3                 Aesthetic Surgery Journal  ...  OpenAccess
4  American Journal of Clinical Dermatology  ...  OpenAccess

[5 rows x 4 columns]

In [15]:
big_df = df.append(df2)
big_df = big_df.replace(-1,np.nan)

In [16]:
big_df.head()

JournalName  ...        Type
0                       Academic Pediatrics  ...  OpenAccess
1                         Acta Orthopaedica  ...  OpenAccess
2              Advances in Medical Sciences  ...  OpenAccess
3                 Aesthetic Surgery Journal  ...  OpenAccess
4  American Journal of Clinical Dermatology  ...  OpenAccess

[5 rows x 4 columns]

In [17]:
big_df.tail()

JournalName  ImpactFactor2020        Source Type
697                 Science advances               NaN  TopCitations  SCI
698         The Lancet Global Health               NaN  TopCitations  SCI
699  Light: Science and Applications               NaN  TopCitations  SCI
700           Nucleic Acids Research               NaN  TopCitations  SCI
701                Physical Review X               NaN  TopCitations  SCI

Get ISSN Number and Journal Metrics

In [18]:
!pip install crossrefapi

  Created wheel for crossrefapi: filename=crossrefapi-1.5.0-cp37-none-any.whl size=15720 sha256=34d7bb827fce64a4bb7e4240f2602a691be1b757294ac89a0fa92fe32f5021b9
  Stored in directory: /root/.cache/pip/wheels/73/71/97/9f4adb0f1b5e0406d6b0b52c6e1418ed1aadf4565ca763604a
Successfully built crossrefapi


In [19]:
from crossref.restful import Journals
journals = Journals()

In [20]:
journals.count()

91965

```
Example:
 |          >>> from crossref.restful import Journals
 |          >>> journals = Journals().query('Public Health', 'Health Science')
 |          >>> journals.url
 |          'https://api.crossref.org/journals?query=Public+Health+Health+Science'
 |          >>> next(iter(journals))
 |          {'last-status-check-time': None, 'counts': None, 'coverage': None,
 |          'publisher': 'ScopeMed International Medical Journal Managment and Indexing System',
 |          'flags': None, 'breakdowns': None, 'ISSN': ['2320-4664', '2277-338X'],
 |          'title': 'International Journal of Medical Science and Public Health'}
```

In [21]:
help(journals)

Help on Journals in module crossref.restful object:

class Journals(Endpoint)
 |  Journals(request_url=None, request_params=None, context=None, etiquette=None, throttle=True, crossref_plus_token=None)
 |  
 |  Method resolution order:
 |      Journals
 |      Endpoint
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  journal(self, issn, only_message=True)
 |      This method retrieve a json with the given ISSN metadata
 |      
 |      args: Journal ISSN (String)
 |      
 |      return: Journal JSON data
 |      
 |      Example:
 |          >>> from crossref.restful import Journals
 |          >>> journals = Journals()
 |          >>> journals.journal('2277-338X')
 |          {'last-status-check-time': None, 'counts': None, 'coverage': None,
 |          'publisher': 'ScopeMed International Medical Journal Managment and Indexing System',
 |          'flags': None, 'breakdowns': None, 'ISSN': ['2320-4664', '2277-338X'],
 |          'title': 'International Journal of Medic

In [22]:
search_journals = journals.query('Academic Pediatrics')
resp = next(iter(search_journals))

In [23]:
search_journals.url

'https://api.crossref.org/journals?query=Academic+Pediatrics'

In [24]:
resp

{'ISSN': ['2474-7521', '2474-7521'],
 'breakdowns': {'dois-by-issued-year': [[2016, 46],
   [2017, 41],
   [2018, 37],
   [2019, 34],
   [2020, 33],
   [2015, 2],
   [2021, 1]]},
 'counts': {'backfile-dois': 126, 'current-dois': 68, 'total-dois': 194},
 'coverage': {'abstracts-backfile': 0.0,
  'abstracts-current': 0.0,
  'affiliations-backfile': 0.0,
  'affiliations-current': 0.0,
  'award-numbers-backfile': 0.0,
  'award-numbers-current': 0.0,
  'funders-backfile': 0.0,
  'funders-current': 0.0,
  'licenses-backfile': 0.0,
  'licenses-current': 0.0,
  'open-references-backfile': 0.0,
  'open-references-current': 0.0,
  'orcids-backfile': 0.0,
  'orcids-current': 0.0,
  'references-backfile': 0.0,
  'references-current': 0.0,
  'resource-links-backfile': 0.0,
  'resource-links-current': 0.0,
  'similarity-checking-backfile': 0.0,
  'similarity-checking-current': 0.0,
  'update-policies-backfile': 0.0,
  'update-policies-current': 0.0},
 'coverage-type': {'all': {'abstracts': 0.0,
   '

### Interests
```
'ISSN': ['2474-7521', '2474-7521'],
 'breakdowns': {'dois-by-issued-year': [[2016, 46],
   [2017, 41],
   [2018, 37],
   [2019, 34],
   [2020, 33],
   [2015, 2],
   [2021, 1]]},
 'counts': {'backfile-dois': 126, 'current-dois': 68, 'total-dois': 194}
'publisher': 'Juniper Publishers',
 'subjects': [],
 'title': 'Academic Journal of Pediatrics & Neonatology'
 ```

In [25]:
import json

with open('data.json', 'w') as fp:
    json.dump(resp, fp)

In [26]:
def create_dir(dir, v=1):
    """
    Creates a directory without throwing an error if directory already exists.
    dir : The directory to be created.
    v : Verbosity
    """
    if not os.path.exists(dir):
        os.makedirs(dir)
        if v:
            print("Created Directory : ", dir)
        return 1
    else:
        if v:
            print("Directory already existed : ", dir)
        return 0

Journals_Metadata_Path = "Journals_Metadata"
create_dir(Journals_Metadata_Path)

from copy import deepcopy

def extract_data(attrs,resp):
  try:
    if len(attrs)==1:
      return resp[attrs[0]]
    resp_new= deepcopy(resp)
    for att in attrs:
      resp_new = resp_new[att]
    return resp_new
  except:
    return np.nan

def calc(data):
  res=0
  try:
    for year,val in data:
      res+=val
  except:
    pass
  return res

def load_JSON(fpath):
  with open(fpath) as json_file:
    data = json.load(json_file)
  return data

def get_details(journal_name):
  JSON_FILE_PATH = os.path.join(Journals_Metadata_Path,journal_name+'.json')
  resp={}
  if os.path.exists(JSON_FILE_PATH):
    resp = load_JSON(JSON_FILE_PATH)
  if resp=={}:
    try:
      search_journals = journals.query(journal_name)
      resp = next(iter(search_journals))
    except:
      resp={}
      pass
    create_dir(os.path.dirname(JSON_FILE_PATH))
    with open(JSON_FILE_PATH, 'w') as fp:
      json.dump(resp, fp)
  """
  Data = {"Title": resp['title'],
          "Publisher": resp['publisher'],
          "ISSN" : resp['ISSN'],
          "DoIsbyYear": resp['breakdowns']['dois-by-issued-year'],
          "TotalDoIs": calc(resp['breakdowns']['dois-by-issued-year']),
          "BackFileDoIs": resp['counts']['backfile-dois'],
          "CurrentDoIs" : resp['counts']['current-dois'],
          "TotalDoIs" : resp['counts']['total-dois'],
          'Subjects' : resp['subjects']
          }
  """
  Data = {"Title": extract_data(['title'],resp),
          "Publisher": extract_data(['publisher'],resp),
          "ISSN" : extract_data(['ISSN'],resp),
          "DoIsbyYear": extract_data(['breakdowns','dois-by-issued-year'],resp),
          "TotalDoIs": calc(extract_data(['breakdowns','dois-by-issued-year'],resp)),
          "BackFileDoIs": extract_data(['counts','backfile-dois'],resp),
          "CurrentDoIs" : extract_data(['counts','current-dois'],resp),
          "TotalDoIs" : extract_data(['counts','total-dois'],resp),
          'Subjects' : extract_data(['subjects'],resp),
          'JSON_FILE_PATH':JSON_FILE_PATH
          }
  return Data

get_details(journal_name="The Lancet Global Health")

Created Directory :  Journals_Metadata
Directory already existed :  Journals_Metadata


{'BackFileDoIs': 1707,
 'CurrentDoIs': 1052,
 'DoIsbyYear': [[2019, 435],
  [2020, 399],
  [2018, 390],
  [2017, 357],
  [2016, 308],
  [2014, 280],
  [2015, 272],
  [2021, 218],
  [2013, 100]],
 'ISSN': ['2214-109X'],
 'JSON_FILE_PATH': 'Journals_Metadata/The Lancet Global Health.json',
 'Publisher': 'Elsevier ',
 'Subjects': [{'ASJC': 2700, 'name': 'General Medicine'}],
 'Title': 'The Lancet Global Health',
 'TotalDoIs': 2759}

In [27]:
!pip install selenium
!apt-get update # to update ubuntu to correctly run apt install
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin
import sys
sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')

from selenium import webdriver
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--window-size=1024x768")
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
wd = webdriver.Chrome('chromedriver',chrome_options=chrome_options)

def ask_google(query):

    # Search for query
    query = query.replace(' ', '+')

    wd.get('http://www.google.com/search?q=' + query)

    # Get text from Google answer box

    answer = wd.execute_script(
            "return document.elementFromPoint(arguments[0], arguments[1]);",
            350, 230).text

    return answer

     |████████████████████████████████| 911kB 3.9MB/s 
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:2 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease [3,626 B]
Ign:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Ign:4 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Get:5 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release [697 B]
Get:6 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease [15.9 kB]
Hit:7 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:8 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Get:9 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release.gpg [836 B]
Get:10 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:11 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ P

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:14: DeprecationWarning: use options instead of chrome_options
  


In [28]:
ask_google(query="impact factor Academic Journal of Pediatrics & Neonatology")

'5.417'

In [29]:
import re
def get_IF(journal_name):
  query = f"impact factor {journal_name}"
  res = ask_google(query)
  # print(res)
  try:
    res = float(res)
  except:
    new_res = re.findall(r"[-+]?\d*\.?\d+|\d+", res)
    # print(new_res)
    for res in new_res:
      if float(res)<100 and float(res)>0:
        return float(res)
    res = np.nan
    pass
  return res

get_IF("The Lancet Global Health")

21.597

In [30]:
big_df.head()

JournalName  ...        Type
0                       Academic Pediatrics  ...  OpenAccess
1                         Acta Orthopaedica  ...  OpenAccess
2              Advances in Medical Sciences  ...  OpenAccess
3                 Aesthetic Surgery Journal  ...  OpenAccess
4  American Journal of Clinical Dermatology  ...  OpenAccess

[5 rows x 4 columns]

```
Data = {"Title": extract_data(['title'],resp),
          "Publisher": extract_data(['publisher'],resp),
          "ISSN" : extract_data(['ISSN'],resp),
          "DoIsbyYear": extract_data(['breakdowns','dois-by-issued-year'],resp),
          "TotalDoIs": calc(extract_data(['breakdowns','dois-by-issued-year'],resp)),
          "BackFileDoIs": extract_data(['counts','backfile-dois'],resp),
          "CurrentDoIs" : extract_data(['counts','current-dois'],resp),
          "TotalDoIs" : extract_data(['counts','total-dois'],resp),
          'Subjects' : extract_data(['subjects'],resp)
          }
```

Title, Publisher, ISSN, DoIsbyYear, TotalDoIs, BackFileDoIs, CurrentDoIs, Subjects, IF


In [31]:
Title = []
Publisher = []
ISSN = []
DoIsbyYear = []
BackFileDoIs = []
CurrentDoIs = []
TotalDoIs = []
Subjects = []
IF = []
Journals_Metadata_Paths = []



import time
"""time.sleep(5)""" # perform per 50 or 100 iters
import tqdm
for index, row in tqdm.tqdm(big_df.iterrows()):
  if index%50==0:
    time.sleep(5) 
  jname = row["JournalName"]
  Data = get_details(journal_name=jname)
  impact_factor = np.nan
  # print(Data)
  if not Data["Title"]==np.nan:
    impact_factor = get_IF(Data["Title"])
  if impact_factor==np.nan:
    impact_factor = get_IF(jname)
  Title.append(Data["Title"])
  Publisher.append(Data["Publisher"])
  ISSN.append(Data["ISSN"])
  DoIsbyYear.append(Data["DoIsbyYear"])
  BackFileDoIs.append(Data["BackFileDoIs"])
  CurrentDoIs.append(Data["CurrentDoIs"])
  TotalDoIs.append(Data["TotalDoIs"])
  Subjects.append(Data["Subjects"])
  IF.append(impact_factor)
  Journals_Metadata_Paths.append(Data["JSON_FILE_PATH"])


0it [00:00, ?it/s]

Directory already existed :  Journals_Metadata


1it [00:05,  5.52s/it]

Directory already existed :  Journals_Metadata


2it [00:06,  4.16s/it]

Directory already existed :  Journals_Metadata


3it [00:07,  3.23s/it]

Directory already existed :  Journals_Metadata


4it [00:08,  2.67s/it]

Directory already existed :  Journals_Metadata


5it [00:10,  2.29s/it]

Directory already existed :  Journals_Metadata


6it [00:11,  1.97s/it]

Directory already existed :  Journals_Metadata


7it [00:12,  1.80s/it]

Directory already existed :  Journals_Metadata


8it [00:14,  1.58s/it]

Directory already existed :  Journals_Metadata


9it [00:15,  1.45s/it]

Directory already existed :  Journals_Metadata


10it [00:16,  1.37s/it]

Directory already existed :  Journals_Metadata


11it [00:17,  1.25s/it]

Directory already existed :  Journals_Metadata


12it [00:18,  1.21s/it]

Directory already existed :  Journals_Metadata


13it [00:19,  1.15s/it]

Directory already existed :  Journals_Metadata


14it [00:20,  1.16s/it]

Directory already existed :  Journals_Metadata


15it [00:21,  1.14s/it]

Directory already existed :  Journals_Metadata


16it [00:22,  1.16s/it]

Directory already existed :  Journals_Metadata


17it [00:24,  1.18s/it]

Directory already existed :  Journals_Metadata


18it [00:25,  1.18s/it]

Directory already existed :  Journals_Metadata


19it [00:26,  1.15s/it]

Directory already existed :  Journals_Metadata


20it [00:27,  1.09s/it]

Directory already existed :  Journals_Metadata


21it [00:28,  1.13s/it]

Directory already existed :  Journals_Metadata


22it [00:29,  1.13s/it]

Directory already existed :  Journals_Metadata


23it [00:30,  1.12s/it]

Directory already existed :  Journals_Metadata


24it [00:31,  1.11s/it]

Directory already existed :  Journals_Metadata


25it [00:33,  1.15s/it]

Directory already existed :  Journals_Metadata


26it [00:34,  1.16s/it]

Directory already existed :  Journals_Metadata


27it [00:35,  1.11s/it]

Directory already existed :  Journals_Metadata


28it [00:36,  1.15s/it]

Directory already existed :  Journals_Metadata


29it [00:37,  1.13s/it]

Directory already existed :  Journals_Metadata


30it [00:38,  1.10s/it]

Directory already existed :  Journals_Metadata


31it [00:39,  1.07s/it]

Directory already existed :  Journals_Metadata


32it [00:40,  1.10s/it]

Directory already existed :  Journals_Metadata


33it [00:42,  1.20s/it]

Directory already existed :  Journals_Metadata


34it [00:43,  1.15s/it]

Directory already existed :  Journals_Metadata


35it [00:43,  1.03it/s]

Directory already existed :  Journals_Metadata


36it [00:44,  1.03it/s]

Directory already existed :  Journals_Metadata


37it [00:46,  1.25s/it]

Directory already existed :  Journals_Metadata


38it [00:48,  1.27s/it]

Directory already existed :  Journals_Metadata


39it [00:49,  1.22s/it]

Directory already existed :  Journals_Metadata


40it [00:50,  1.16s/it]

Directory already existed :  Journals_Metadata


41it [00:51,  1.08s/it]

Directory already existed :  Journals_Metadata


42it [00:51,  1.02it/s]

Directory already existed :  Journals_Metadata


43it [00:52,  1.04it/s]

Directory already existed :  Journals_Metadata


44it [00:53,  1.03it/s]

Directory already existed :  Journals_Metadata


45it [00:54,  1.01it/s]

Directory already existed :  Journals_Metadata


46it [00:55,  1.08it/s]

Directory already existed :  Journals_Metadata


47it [00:56,  1.06it/s]

Directory already existed :  Journals_Metadata


48it [00:57,  1.03it/s]

Directory already existed :  Journals_Metadata


49it [00:58,  1.01s/it]

Directory already existed :  Journals_Metadata


50it [00:59,  1.03it/s]

Directory already existed :  Journals_Metadata


51it [01:05,  2.60s/it]

Directory already existed :  Journals_Metadata


52it [01:07,  2.19s/it]

Directory already existed :  Journals_Metadata


53it [01:08,  1.90s/it]

Directory already existed :  Journals_Metadata


54it [01:09,  1.70s/it]

Directory already existed :  Journals_Metadata


55it [01:10,  1.57s/it]

Directory already existed :  Journals_Metadata


56it [01:12,  1.44s/it]

Directory already existed :  Journals_Metadata


57it [01:13,  1.43s/it]

Directory already existed :  Journals_Metadata


58it [01:14,  1.45s/it]

Directory already existed :  Journals_Metadata


59it [01:16,  1.39s/it]

Directory already existed :  Journals_Metadata


60it [01:17,  1.35s/it]

Directory already existed :  Journals_Metadata


61it [01:19,  1.43s/it]

Directory already existed :  Journals_Metadata


62it [01:20,  1.52s/it]

Directory already existed :  Journals_Metadata


63it [01:22,  1.47s/it]

Directory already existed :  Journals_Metadata


64it [01:23,  1.38s/it]

Directory already existed :  Journals_Metadata


65it [01:24,  1.37s/it]

Directory already existed :  Journals_Metadata


66it [01:25,  1.35s/it]

Directory already existed :  Journals_Metadata


67it [01:27,  1.37s/it]

Directory already existed :  Journals_Metadata


68it [01:28,  1.40s/it]

Directory already existed :  Journals_Metadata


69it [01:29,  1.22s/it]

Directory already existed :  Journals_Metadata


70it [01:30,  1.09s/it]

Directory already existed :  Journals_Metadata


71it [01:31,  1.00s/it]

Directory already existed :  Journals_Metadata


72it [01:32,  1.04it/s]

Directory already existed :  Journals_Metadata


73it [01:32,  1.06it/s]

Directory already existed :  Journals_Metadata


74it [01:33,  1.10it/s]

Directory already existed :  Journals_Metadata


75it [01:34,  1.06it/s]

Directory already existed :  Journals_Metadata


76it [01:36,  1.01s/it]

Directory already existed :  Journals_Metadata


77it [01:36,  1.04it/s]

Directory already existed :  Journals_Metadata


78it [01:37,  1.02it/s]

Directory already existed :  Journals_Metadata


79it [01:38,  1.10it/s]

Directory already existed :  Journals_Metadata


80it [01:39,  1.08it/s]

Directory already existed :  Journals_Metadata


81it [01:40,  1.12it/s]

Directory already existed :  Journals_Metadata


82it [01:41,  1.03s/it]

Directory already existed :  Journals_Metadata


83it [01:43,  1.15s/it]

Directory already existed :  Journals_Metadata


84it [01:44,  1.22s/it]

Directory already existed :  Journals_Metadata


85it [01:45,  1.27s/it]

Directory already existed :  Journals_Metadata


86it [01:47,  1.25s/it]

Directory already existed :  Journals_Metadata


87it [01:48,  1.25s/it]

Directory already existed :  Journals_Metadata


88it [01:49,  1.24s/it]

Directory already existed :  Journals_Metadata


89it [01:51,  1.29s/it]

Directory already existed :  Journals_Metadata


90it [01:51,  1.17s/it]

Directory already existed :  Journals_Metadata


91it [01:52,  1.05s/it]

Directory already existed :  Journals_Metadata


92it [01:53,  1.06it/s]

Directory already existed :  Journals_Metadata


93it [01:54,  1.14it/s]

Directory already existed :  Journals_Metadata


94it [01:54,  1.14it/s]

Directory already existed :  Journals_Metadata


95it [01:56,  1.01s/it]

Directory already existed :  Journals_Metadata


96it [01:57,  1.05s/it]

Directory already existed :  Journals_Metadata


97it [01:58,  1.11s/it]

Directory already existed :  Journals_Metadata


98it [02:00,  1.18s/it]

Directory already existed :  Journals_Metadata


99it [02:01,  1.16s/it]

Directory already existed :  Journals_Metadata


100it [02:02,  1.11s/it]

Directory already existed :  Journals_Metadata


101it [02:07,  2.53s/it]

Directory already existed :  Journals_Metadata


102it [02:09,  2.08s/it]

Directory already existed :  Journals_Metadata


103it [02:09,  1.68s/it]

Directory already existed :  Journals_Metadata


104it [02:10,  1.48s/it]

Directory already existed :  Journals_Metadata


105it [02:11,  1.33s/it]

Directory already existed :  Journals_Metadata


106it [02:12,  1.14s/it]

Directory already existed :  Journals_Metadata


107it [02:13,  1.22s/it]

Directory already existed :  Journals_Metadata


108it [02:15,  1.27s/it]

Directory already existed :  Journals_Metadata


109it [02:15,  1.10s/it]

Directory already existed :  Journals_Metadata


110it [02:16,  1.06s/it]

Directory already existed :  Journals_Metadata


111it [02:17,  1.02it/s]

Directory already existed :  Journals_Metadata


112it [02:18,  1.01it/s]

Directory already existed :  Journals_Metadata


113it [02:19,  1.03s/it]

Directory already existed :  Journals_Metadata


114it [02:20,  1.03s/it]

Directory already existed :  Journals_Metadata


115it [02:21,  1.03s/it]

Directory already existed :  Journals_Metadata


116it [02:23,  1.11s/it]

Directory already existed :  Journals_Metadata


117it [02:24,  1.06s/it]

Directory already existed :  Journals_Metadata


118it [02:25,  1.05s/it]

Directory already existed :  Journals_Metadata


119it [02:25,  1.02it/s]

Directory already existed :  Journals_Metadata


120it [02:26,  1.11it/s]

Directory already existed :  Journals_Metadata


121it [02:27,  1.10it/s]

Directory already existed :  Journals_Metadata


122it [02:28,  1.04s/it]

Directory already existed :  Journals_Metadata


123it [02:29,  1.03s/it]

Directory already existed :  Journals_Metadata


124it [02:30,  1.00it/s]

Directory already existed :  Journals_Metadata


125it [02:31,  1.02it/s]

Directory already existed :  Journals_Metadata


126it [02:32,  1.10it/s]

Directory already existed :  Journals_Metadata


127it [02:33,  1.11it/s]

Directory already existed :  Journals_Metadata


128it [02:34,  1.01s/it]

Directory already existed :  Journals_Metadata


129it [02:36,  1.11s/it]

Directory already existed :  Journals_Metadata


130it [02:37,  1.15s/it]

Directory already existed :  Journals_Metadata


131it [02:38,  1.19s/it]

Directory already existed :  Journals_Metadata


132it [02:39,  1.05s/it]

Directory already existed :  Journals_Metadata


133it [02:40,  1.05it/s]

Directory already existed :  Journals_Metadata


134it [02:40,  1.07it/s]

Directory already existed :  Journals_Metadata


135it [02:41,  1.03it/s]

Directory already existed :  Journals_Metadata


136it [02:43,  1.01it/s]

Directory already existed :  Journals_Metadata


137it [02:44,  1.01it/s]

Directory already existed :  Journals_Metadata


138it [02:44,  1.03it/s]

Directory already existed :  Journals_Metadata


139it [02:46,  1.07s/it]

Directory already existed :  Journals_Metadata


140it [02:47,  1.16s/it]

Directory already existed :  Journals_Metadata


141it [02:48,  1.06s/it]

Directory already existed :  Journals_Metadata


142it [02:49,  1.01it/s]

Directory already existed :  Journals_Metadata


143it [02:50,  1.01s/it]

Directory already existed :  Journals_Metadata


144it [02:51,  1.04it/s]

Directory already existed :  Journals_Metadata


145it [02:52,  1.07it/s]

Directory already existed :  Journals_Metadata


146it [02:53,  1.12s/it]

Directory already existed :  Journals_Metadata


147it [02:54,  1.14s/it]

Directory already existed :  Journals_Metadata


148it [02:56,  1.20s/it]

Directory already existed :  Journals_Metadata


149it [02:57,  1.23s/it]

Directory already existed :  Journals_Metadata


150it [02:58,  1.14s/it]

Directory already existed :  Journals_Metadata


151it [03:04,  2.60s/it]

Directory already existed :  Journals_Metadata


152it [03:05,  2.26s/it]

Directory already existed :  Journals_Metadata


153it [03:06,  1.86s/it]

Directory already existed :  Journals_Metadata


154it [03:07,  1.56s/it]

Directory already existed :  Journals_Metadata


155it [03:08,  1.42s/it]

Directory already existed :  Journals_Metadata


156it [03:09,  1.25s/it]

Directory already existed :  Journals_Metadata


157it [03:11,  1.31s/it]

Directory already existed :  Journals_Metadata


158it [03:12,  1.22s/it]

Directory already existed :  Journals_Metadata


159it [03:12,  1.08s/it]

Directory already existed :  Journals_Metadata


160it [03:13,  1.01it/s]

Directory already existed :  Journals_Metadata


161it [03:14,  1.01s/it]

Directory already existed :  Journals_Metadata


162it [03:15,  1.03s/it]

Directory already existed :  Journals_Metadata


163it [03:16,  1.07it/s]

Directory already existed :  Journals_Metadata


164it [03:17,  1.12it/s]

Directory already existed :  Journals_Metadata


165it [03:18,  1.08it/s]

Directory already existed :  Journals_Metadata


166it [03:19,  1.06it/s]

Directory already existed :  Journals_Metadata


167it [03:19,  1.14it/s]

Directory already existed :  Journals_Metadata


168it [03:20,  1.10it/s]

Directory already existed :  Journals_Metadata


169it [03:21,  1.10it/s]

Directory already existed :  Journals_Metadata


170it [03:22,  1.16it/s]

Directory already existed :  Journals_Metadata


171it [03:23,  1.04s/it]

Directory already existed :  Journals_Metadata


172it [03:26,  1.34s/it]

Directory already existed :  Journals_Metadata


173it [03:26,  1.21s/it]

Directory already existed :  Journals_Metadata


174it [03:27,  1.13s/it]

Directory already existed :  Journals_Metadata


175it [03:28,  1.07s/it]

Directory already existed :  Journals_Metadata


176it [03:30,  1.11s/it]

Directory already existed :  Journals_Metadata


177it [03:30,  1.02s/it]

Directory already existed :  Journals_Metadata


178it [03:31,  1.02s/it]

Directory already existed :  Journals_Metadata


179it [03:33,  1.16s/it]

Directory already existed :  Journals_Metadata


180it [03:34,  1.17s/it]

Directory already existed :  Journals_Metadata


181it [03:35,  1.13s/it]

Directory already existed :  Journals_Metadata


182it [03:36,  1.17s/it]

Directory already existed :  Journals_Metadata


183it [03:37,  1.15s/it]

Directory already existed :  Journals_Metadata


184it [03:39,  1.23s/it]

Directory already existed :  Journals_Metadata


185it [03:40,  1.13s/it]

Directory already existed :  Journals_Metadata


188it [03:42,  1.17it/s]

Directory already existed :  Journals_Metadata


191it [03:45,  1.17it/s]

Directory already existed :  Journals_Metadata


215it [04:08,  1.34it/s]

Directory already existed :  Journals_Metadata


222it [04:13,  1.19it/s]

Directory already existed :  Journals_Metadata


232it [04:21,  1.41it/s]

Directory already existed :  Journals_Metadata


248it [04:33,  1.36it/s]

Directory already existed :  Journals_Metadata


319it [05:37,  1.22it/s]

Directory already existed :  Journals_Metadata


321it [05:39,  1.17it/s]

Directory already existed :  Journals_Metadata


362it [06:15,  1.28it/s]

Directory already existed :  Journals_Metadata


367it [06:20,  1.17it/s]

Directory already existed :  Journals_Metadata


368it [06:21,  1.13it/s]

Directory already existed :  Journals_Metadata


369it [06:27,  2.42s/it]

Directory already existed :  Journals_Metadata


370it [06:28,  2.00s/it]

Directory already existed :  Journals_Metadata


371it [06:29,  1.71s/it]

Directory already existed :  Journals_Metadata


372it [06:30,  1.50s/it]

Directory already existed :  Journals_Metadata


373it [06:31,  1.37s/it]

Directory already existed :  Journals_Metadata


374it [06:32,  1.26s/it]

Directory already existed :  Journals_Metadata


375it [06:33,  1.10s/it]

Directory already existed :  Journals_Metadata


376it [06:34,  1.07s/it]

Directory already existed :  Journals_Metadata


377it [06:35,  1.01s/it]

Directory already existed :  Journals_Metadata


378it [06:35,  1.01it/s]

Directory already existed :  Journals_Metadata


379it [06:36,  1.02it/s]

Directory already existed :  Journals_Metadata


380it [06:37,  1.07it/s]

Directory already existed :  Journals_Metadata


381it [06:38,  1.13it/s]

Directory already existed :  Journals_Metadata


382it [06:39,  1.10it/s]

Directory already existed :  Journals_Metadata


383it [06:40,  1.08it/s]

Directory already existed :  Journals_Metadata


384it [06:41,  1.17it/s]

Directory already existed :  Journals_Metadata


385it [06:42,  1.14it/s]

Directory already existed :  Journals_Metadata


386it [06:42,  1.17it/s]

Directory already existed :  Journals_Metadata


387it [06:43,  1.14it/s]

Directory already existed :  Journals_Metadata


388it [06:44,  1.11it/s]

Directory already existed :  Journals_Metadata


389it [06:45,  1.04it/s]

Directory already existed :  Journals_Metadata


390it [06:47,  1.01s/it]

Directory already existed :  Journals_Metadata


391it [06:47,  1.03it/s]

Directory already existed :  Journals_Metadata


392it [06:48,  1.04it/s]

Directory already existed :  Journals_Metadata


393it [06:49,  1.11it/s]

Directory already existed :  Journals_Metadata


394it [06:50,  1.08it/s]

Directory already existed :  Journals_Metadata


395it [06:51,  1.04it/s]

Directory already existed :  Journals_Metadata


396it [06:52,  1.03it/s]

Directory already existed :  Journals_Metadata


397it [06:53,  1.07it/s]

Directory already existed :  Journals_Metadata


398it [06:54,  1.12it/s]

Directory already existed :  Journals_Metadata


399it [06:55,  1.15it/s]

Directory already existed :  Journals_Metadata


400it [06:55,  1.17it/s]

Directory already existed :  Journals_Metadata


401it [06:56,  1.13it/s]

Directory already existed :  Journals_Metadata


402it [06:57,  1.13it/s]

Directory already existed :  Journals_Metadata


403it [06:58,  1.17it/s]

Directory already existed :  Journals_Metadata


404it [06:59,  1.17it/s]

Directory already existed :  Journals_Metadata


405it [07:00,  1.13it/s]

Directory already existed :  Journals_Metadata


406it [07:01,  1.17it/s]

Directory already existed :  Journals_Metadata


407it [07:01,  1.18it/s]

Directory already existed :  Journals_Metadata


408it [07:02,  1.20it/s]

Directory already existed :  Journals_Metadata


409it [07:03,  1.20it/s]

Directory already existed :  Journals_Metadata


410it [07:04,  1.20it/s]

Directory already existed :  Journals_Metadata


411it [07:05,  1.16it/s]

Directory already existed :  Journals_Metadata


412it [07:06,  1.08it/s]

Directory already existed :  Journals_Metadata


413it [07:07,  1.07it/s]

Directory already existed :  Journals_Metadata


414it [07:08,  1.05it/s]

Directory already existed :  Journals_Metadata


415it [07:09,  1.09it/s]

Directory already existed :  Journals_Metadata


416it [07:10,  1.05it/s]

Directory already existed :  Journals_Metadata


417it [07:11,  1.05it/s]

Directory already existed :  Journals_Metadata


418it [07:13,  1.23s/it]

Directory already existed :  Journals_Metadata


419it [07:21,  3.26s/it]

Directory already existed :  Journals_Metadata


420it [07:21,  2.55s/it]

Directory already existed :  Journals_Metadata


421it [07:22,  2.08s/it]

Directory already existed :  Journals_Metadata


422it [07:23,  1.77s/it]

Directory already existed :  Journals_Metadata


423it [07:24,  1.48s/it]

Directory already existed :  Journals_Metadata


424it [07:25,  1.31s/it]

Directory already existed :  Journals_Metadata


425it [07:26,  1.18s/it]

Directory already existed :  Journals_Metadata


426it [07:27,  1.14s/it]

Directory already existed :  Journals_Metadata


427it [07:28,  1.06s/it]

Directory already existed :  Journals_Metadata


428it [07:29,  1.05s/it]

Directory already existed :  Journals_Metadata


429it [07:30,  1.08s/it]

Directory already existed :  Journals_Metadata


430it [07:31,  1.02s/it]

Directory already existed :  Journals_Metadata


431it [07:32,  1.02it/s]

Directory already existed :  Journals_Metadata


432it [07:33,  1.08it/s]

Directory already existed :  Journals_Metadata


433it [07:33,  1.15it/s]

Directory already existed :  Journals_Metadata


434it [07:34,  1.12it/s]

Directory already existed :  Journals_Metadata


435it [07:35,  1.13it/s]

Directory already existed :  Journals_Metadata


436it [07:36,  1.20it/s]

Directory already existed :  Journals_Metadata


437it [07:37,  1.16it/s]

Directory already existed :  Journals_Metadata


438it [07:38,  1.13it/s]

Directory already existed :  Journals_Metadata


439it [07:39,  1.16it/s]

Directory already existed :  Journals_Metadata


441it [07:40,  1.24it/s]

Directory already existed :  Journals_Metadata


442it [07:41,  1.27it/s]

Directory already existed :  Journals_Metadata


443it [07:42,  1.18it/s]

Directory already existed :  Journals_Metadata


444it [07:43,  1.18it/s]

Directory already existed :  Journals_Metadata


445it [07:44,  1.17it/s]

Directory already existed :  Journals_Metadata


446it [07:45,  1.10it/s]

Directory already existed :  Journals_Metadata


447it [07:48,  1.58s/it]

Directory already existed :  Journals_Metadata


448it [07:59,  4.43s/it]

Directory already existed :  Journals_Metadata


449it [08:02,  3.94s/it]

Directory already existed :  Journals_Metadata


450it [08:17,  7.20s/it]

Directory already existed :  Journals_Metadata


451it [08:27,  8.30s/it]

Directory already existed :  Journals_Metadata


452it [08:34,  7.69s/it]

Directory already existed :  Journals_Metadata


453it [08:35,  5.64s/it]

Directory already existed :  Journals_Metadata


454it [08:36,  4.26s/it]

Directory already existed :  Journals_Metadata


455it [08:37,  3.28s/it]

Directory already existed :  Journals_Metadata


456it [08:38,  2.60s/it]

Directory already existed :  Journals_Metadata


457it [08:39,  2.13s/it]

Directory already existed :  Journals_Metadata


458it [08:40,  1.77s/it]

Directory already existed :  Journals_Metadata


459it [08:40,  1.48s/it]

Directory already existed :  Journals_Metadata


460it [08:41,  1.32s/it]

Directory already existed :  Journals_Metadata


461it [08:42,  1.15s/it]

Directory already existed :  Journals_Metadata


462it [08:43,  1.10s/it]

Directory already existed :  Journals_Metadata


463it [08:44,  1.00it/s]

Directory already existed :  Journals_Metadata


464it [08:45,  1.03it/s]

Directory already existed :  Journals_Metadata


465it [08:46,  1.05it/s]

Directory already existed :  Journals_Metadata


466it [08:46,  1.08it/s]

Directory already existed :  Journals_Metadata


467it [08:47,  1.14it/s]

Directory already existed :  Journals_Metadata


468it [08:48,  1.07it/s]

Directory already existed :  Journals_Metadata


469it [08:54,  2.46s/it]

Directory already existed :  Journals_Metadata


470it [08:55,  1.97s/it]

Directory already existed :  Journals_Metadata


471it [08:56,  1.67s/it]

Directory already existed :  Journals_Metadata


472it [08:57,  1.45s/it]

Directory already existed :  Journals_Metadata


473it [08:58,  1.26s/it]

Directory already existed :  Journals_Metadata


474it [08:59,  1.15s/it]

Directory already existed :  Journals_Metadata


475it [09:00,  1.10s/it]

Directory already existed :  Journals_Metadata


476it [09:01,  1.03s/it]

Directory already existed :  Journals_Metadata


477it [09:02,  1.04s/it]

Directory already existed :  Journals_Metadata


478it [09:03,  1.02it/s]

Directory already existed :  Journals_Metadata


479it [09:03,  1.05it/s]

Directory already existed :  Journals_Metadata


480it [09:04,  1.10it/s]

Directory already existed :  Journals_Metadata


481it [09:05,  1.18it/s]

Directory already existed :  Journals_Metadata


482it [09:06,  1.26it/s]

Directory already existed :  Journals_Metadata


483it [09:07,  1.20it/s]

Directory already existed :  Journals_Metadata


484it [09:07,  1.22it/s]

Directory already existed :  Journals_Metadata


485it [09:08,  1.15it/s]

Directory already existed :  Journals_Metadata


486it [09:09,  1.06it/s]

Directory already existed :  Journals_Metadata


487it [09:11,  1.01it/s]

Directory already existed :  Journals_Metadata


488it [09:11,  1.07it/s]

Directory already existed :  Journals_Metadata


489it [09:12,  1.00it/s]

Directory already existed :  Journals_Metadata


490it [09:14,  1.03s/it]

Directory already existed :  Journals_Metadata


491it [09:14,  1.01it/s]

Directory already existed :  Journals_Metadata


492it [09:15,  1.04it/s]

Directory already existed :  Journals_Metadata


493it [09:16,  1.13it/s]

Directory already existed :  Journals_Metadata


494it [09:17,  1.06it/s]

Directory already existed :  Journals_Metadata


495it [09:18,  1.13it/s]

Directory already existed :  Journals_Metadata


496it [09:19,  1.18it/s]

Directory already existed :  Journals_Metadata


497it [09:19,  1.21it/s]

Directory already existed :  Journals_Metadata


498it [09:20,  1.26it/s]

Directory already existed :  Journals_Metadata


499it [09:21,  1.26it/s]

Directory already existed :  Journals_Metadata


500it [09:22,  1.21it/s]

Directory already existed :  Journals_Metadata


501it [09:23,  1.21it/s]

Directory already existed :  Journals_Metadata


502it [09:24,  1.15it/s]

Directory already existed :  Journals_Metadata


503it [09:24,  1.19it/s]

Directory already existed :  Journals_Metadata


504it [09:25,  1.11it/s]

Directory already existed :  Journals_Metadata


505it [09:26,  1.08it/s]

Directory already existed :  Journals_Metadata


506it [09:27,  1.04it/s]

Directory already existed :  Journals_Metadata


507it [09:29,  1.06s/it]

Directory already existed :  Journals_Metadata


508it [09:30,  1.02s/it]

Directory already existed :  Journals_Metadata


509it [09:31,  1.00it/s]

Directory already existed :  Journals_Metadata


510it [09:31,  1.08it/s]

Directory already existed :  Journals_Metadata


511it [09:32,  1.07it/s]

Directory already existed :  Journals_Metadata


512it [09:33,  1.14it/s]

Directory already existed :  Journals_Metadata


513it [09:34,  1.10it/s]

Directory already existed :  Journals_Metadata


514it [09:35,  1.05it/s]

Directory already existed :  Journals_Metadata


515it [09:36,  1.07it/s]

Directory already existed :  Journals_Metadata


516it [09:37,  1.12it/s]

Directory already existed :  Journals_Metadata


517it [09:38,  1.04it/s]

Directory already existed :  Journals_Metadata


518it [09:39,  1.10it/s]

Directory already existed :  Journals_Metadata


519it [09:45,  2.40s/it]

Directory already existed :  Journals_Metadata


520it [09:45,  1.92s/it]

Directory already existed :  Journals_Metadata


521it [09:46,  1.58s/it]

Directory already existed :  Journals_Metadata


522it [09:47,  1.42s/it]

Directory already existed :  Journals_Metadata


523it [09:48,  1.24s/it]

Directory already existed :  Journals_Metadata


524it [09:49,  1.17s/it]

Directory already existed :  Journals_Metadata


525it [09:50,  1.16s/it]

Directory already existed :  Journals_Metadata


526it [09:51,  1.16s/it]

Directory already existed :  Journals_Metadata


527it [09:53,  1.16s/it]

Directory already existed :  Journals_Metadata


528it [09:54,  1.14s/it]

Directory already existed :  Journals_Metadata


529it [09:55,  1.10s/it]

Directory already existed :  Journals_Metadata


530it [09:56,  1.12s/it]

Directory already existed :  Journals_Metadata


531it [09:57,  1.08s/it]

Directory already existed :  Journals_Metadata


532it [09:58,  1.02s/it]

Directory already existed :  Journals_Metadata


533it [09:59,  1.07s/it]

Directory already existed :  Journals_Metadata


534it [10:00,  1.00s/it]

Directory already existed :  Journals_Metadata


535it [10:01,  1.04it/s]

Directory already existed :  Journals_Metadata


536it [10:01,  1.07it/s]

Directory already existed :  Journals_Metadata


537it [10:03,  1.02s/it]

Directory already existed :  Journals_Metadata


538it [10:04,  1.04s/it]

Directory already existed :  Journals_Metadata


539it [10:05,  1.13s/it]

Directory already existed :  Journals_Metadata


540it [10:06,  1.08s/it]

Directory already existed :  Journals_Metadata


541it [10:07,  1.05s/it]

Directory already existed :  Journals_Metadata


542it [10:08,  1.05s/it]

Directory already existed :  Journals_Metadata


543it [10:09,  1.07s/it]

Directory already existed :  Journals_Metadata


544it [10:10,  1.10s/it]

Directory already existed :  Journals_Metadata


545it [10:12,  1.15s/it]

Directory already existed :  Journals_Metadata


546it [10:13,  1.14s/it]

Directory already existed :  Journals_Metadata


547it [10:14,  1.17s/it]

Directory already existed :  Journals_Metadata


548it [10:15,  1.17s/it]

Directory already existed :  Journals_Metadata


549it [10:16,  1.13s/it]

Directory already existed :  Journals_Metadata


550it [10:18,  1.23s/it]

Directory already existed :  Journals_Metadata


551it [10:19,  1.18s/it]

Directory already existed :  Journals_Metadata


552it [10:20,  1.14s/it]

Directory already existed :  Journals_Metadata


553it [10:21,  1.24s/it]

Directory already existed :  Journals_Metadata


554it [10:22,  1.20s/it]

Created Directory :  Journals_Metadata/Africa Development


555it [10:24,  1.23s/it]

Directory already existed :  Journals_Metadata


556it [10:25,  1.25s/it]

Directory already existed :  Journals_Metadata


557it [10:26,  1.13s/it]

Directory already existed :  Journals_Metadata


558it [10:27,  1.17s/it]

Directory already existed :  Journals_Metadata


559it [10:28,  1.13s/it]

Directory already existed :  Journals_Metadata


560it [10:29,  1.13s/it]

Directory already existed :  Journals_Metadata


561it [10:30,  1.04s/it]

Directory already existed :  Journals_Metadata


562it [10:31,  1.07s/it]

Directory already existed :  Journals_Metadata


563it [10:32,  1.11s/it]

Directory already existed :  Journals_Metadata


564it [10:34,  1.17s/it]

Directory already existed :  Journals_Metadata


565it [10:35,  1.11s/it]

Directory already existed :  Journals_Metadata


566it [10:36,  1.13s/it]

Directory already existed :  Journals_Metadata


567it [10:37,  1.12s/it]

Directory already existed :  Journals_Metadata


568it [10:38,  1.12s/it]

Directory already existed :  Journals_Metadata


569it [10:44,  2.63s/it]

Directory already existed :  Journals_Metadata


570it [10:45,  2.22s/it]

Directory already existed :  Journals_Metadata


571it [10:47,  1.88s/it]

Directory already existed :  Journals_Metadata


572it [10:47,  1.58s/it]

Directory already existed :  Journals_Metadata


573it [10:48,  1.37s/it]

Directory already existed :  Journals_Metadata


574it [10:49,  1.26s/it]

Directory already existed :  Journals_Metadata


575it [10:50,  1.17s/it]

Directory already existed :  Journals_Metadata


576it [10:51,  1.17s/it]

Directory already existed :  Journals_Metadata


577it [10:53,  1.19s/it]

Directory already existed :  Journals_Metadata


578it [10:54,  1.20s/it]

Directory already existed :  Journals_Metadata


579it [10:55,  1.15s/it]

Directory already existed :  Journals_Metadata


580it [10:56,  1.16s/it]

Directory already existed :  Journals_Metadata


581it [10:57,  1.15s/it]

Directory already existed :  Journals_Metadata


582it [10:58,  1.13s/it]

Directory already existed :  Journals_Metadata


583it [11:00,  1.15s/it]

Directory already existed :  Journals_Metadata


584it [11:01,  1.20s/it]

Directory already existed :  Journals_Metadata


585it [11:02,  1.14s/it]

Directory already existed :  Journals_Metadata


586it [11:03,  1.03s/it]

Directory already existed :  Journals_Metadata


587it [11:03,  1.03it/s]

Directory already existed :  Journals_Metadata


588it [11:04,  1.03it/s]

Directory already existed :  Journals_Metadata


589it [11:05,  1.07it/s]

Directory already existed :  Journals_Metadata


590it [11:06,  1.08it/s]

Directory already existed :  Journals_Metadata


591it [11:07,  1.01s/it]

Directory already existed :  Journals_Metadata


592it [11:08,  1.00it/s]

Directory already existed :  Journals_Metadata


593it [11:10,  1.04s/it]

Directory already existed :  Journals_Metadata


594it [11:10,  1.01it/s]

Directory already existed :  Journals_Metadata


595it [11:11,  1.02it/s]

Directory already existed :  Journals_Metadata


596it [11:12,  1.02s/it]

Directory already existed :  Journals_Metadata


597it [11:13,  1.03it/s]

Directory already existed :  Journals_Metadata


598it [11:14,  1.01it/s]

Directory already existed :  Journals_Metadata


599it [11:15,  1.01s/it]

Directory already existed :  Journals_Metadata


600it [11:16,  1.03it/s]

Directory already existed :  Journals_Metadata


601it [11:17,  1.00s/it]

Directory already existed :  Journals_Metadata


602it [11:18,  1.05it/s]

Directory already existed :  Journals_Metadata


603it [11:19,  1.01s/it]

Directory already existed :  Journals_Metadata


604it [11:20,  1.02s/it]

Directory already existed :  Journals_Metadata


605it [11:21,  1.01s/it]

Directory already existed :  Journals_Metadata


606it [11:22,  1.04it/s]

Directory already existed :  Journals_Metadata


607it [11:23,  1.02it/s]

Directory already existed :  Journals_Metadata


608it [11:24,  1.02it/s]

Directory already existed :  Journals_Metadata


609it [11:25,  1.04it/s]

Directory already existed :  Journals_Metadata


610it [11:26,  1.02s/it]

Directory already existed :  Journals_Metadata


611it [11:27,  1.02s/it]

Directory already existed :  Journals_Metadata


612it [11:28,  1.00it/s]

Directory already existed :  Journals_Metadata


613it [11:29,  1.01s/it]

Directory already existed :  Journals_Metadata


614it [11:30,  1.00it/s]

Directory already existed :  Journals_Metadata


615it [11:31,  1.00s/it]

Directory already existed :  Journals_Metadata


616it [11:32,  1.01it/s]

Directory already existed :  Journals_Metadata


617it [11:33,  1.00it/s]

Directory already existed :  Journals_Metadata


618it [11:34,  1.08s/it]

Directory already existed :  Journals_Metadata


619it [11:41,  2.60s/it]

Directory already existed :  Journals_Metadata


620it [11:42,  2.13s/it]

Directory already existed :  Journals_Metadata


621it [11:43,  1.89s/it]

Directory already existed :  Journals_Metadata


622it [11:44,  1.73s/it]

Directory already existed :  Journals_Metadata


623it [11:46,  1.56s/it]

Directory already existed :  Journals_Metadata


624it [11:47,  1.43s/it]

Directory already existed :  Journals_Metadata


625it [11:48,  1.44s/it]

Directory already existed :  Journals_Metadata


626it [11:49,  1.35s/it]

Directory already existed :  Journals_Metadata


627it [11:50,  1.23s/it]

Directory already existed :  Journals_Metadata


628it [11:51,  1.15s/it]

Directory already existed :  Journals_Metadata


629it [11:52,  1.19s/it]

Directory already existed :  Journals_Metadata


630it [11:54,  1.19s/it]

Directory already existed :  Journals_Metadata


631it [11:55,  1.23s/it]

Directory already existed :  Journals_Metadata


632it [11:56,  1.24s/it]

Directory already existed :  Journals_Metadata


633it [11:57,  1.15s/it]

Directory already existed :  Journals_Metadata


634it [11:58,  1.08s/it]

Directory already existed :  Journals_Metadata


635it [11:59,  1.04s/it]

Directory already existed :  Journals_Metadata


636it [12:00,  1.02s/it]

Directory already existed :  Journals_Metadata


637it [12:01,  1.03s/it]

Directory already existed :  Journals_Metadata


638it [12:02,  1.01s/it]

Directory already existed :  Journals_Metadata


639it [12:03,  1.02s/it]

Directory already existed :  Journals_Metadata


640it [12:04,  1.05it/s]

Directory already existed :  Journals_Metadata


641it [12:05,  1.07it/s]

Directory already existed :  Journals_Metadata


642it [12:06,  1.08it/s]

Directory already existed :  Journals_Metadata


643it [12:07,  1.06it/s]

Directory already existed :  Journals_Metadata


644it [12:08,  1.03it/s]

Directory already existed :  Journals_Metadata


645it [12:09,  1.05it/s]

Directory already existed :  Journals_Metadata


646it [12:09,  1.10it/s]

Directory already existed :  Journals_Metadata


647it [12:10,  1.11it/s]

Directory already existed :  Journals_Metadata


648it [12:11,  1.11it/s]

Directory already existed :  Journals_Metadata


649it [12:12,  1.12it/s]

Directory already existed :  Journals_Metadata


650it [12:13,  1.08it/s]

Directory already existed :  Journals_Metadata


651it [12:14,  1.10it/s]

Directory already existed :  Journals_Metadata


652it [12:15,  1.13it/s]

Directory already existed :  Journals_Metadata


653it [12:16,  1.10it/s]

Directory already existed :  Journals_Metadata


654it [12:17,  1.05it/s]

Directory already existed :  Journals_Metadata


655it [12:18,  1.03it/s]

Directory already existed :  Journals_Metadata


656it [12:19,  1.03it/s]

Directory already existed :  Journals_Metadata


657it [12:20,  1.03it/s]

Directory already existed :  Journals_Metadata


658it [12:21,  1.03it/s]

Directory already existed :  Journals_Metadata


659it [12:22,  1.05it/s]

Directory already existed :  Journals_Metadata


660it [12:23,  1.07it/s]

Directory already existed :  Journals_Metadata


661it [12:23,  1.13it/s]

Directory already existed :  Journals_Metadata


662it [12:24,  1.19it/s]

Directory already existed :  Journals_Metadata


663it [12:25,  1.20it/s]

Directory already existed :  Journals_Metadata


664it [12:26,  1.25it/s]

Directory already existed :  Journals_Metadata


665it [12:27,  1.18it/s]

Directory already existed :  Journals_Metadata


666it [12:27,  1.16it/s]

Directory already existed :  Journals_Metadata


667it [12:28,  1.19it/s]

Directory already existed :  Journals_Metadata


668it [12:29,  1.18it/s]

Directory already existed :  Journals_Metadata


669it [12:35,  2.38s/it]

Directory already existed :  Journals_Metadata


670it [12:36,  1.93s/it]

Directory already existed :  Journals_Metadata


671it [12:37,  1.65s/it]

Directory already existed :  Journals_Metadata


672it [12:38,  1.45s/it]

Directory already existed :  Journals_Metadata


673it [12:39,  1.33s/it]

Directory already existed :  Journals_Metadata


674it [12:40,  1.18s/it]

Directory already existed :  Journals_Metadata


675it [12:41,  1.13s/it]

Directory already existed :  Journals_Metadata


676it [12:42,  1.04s/it]

Directory already existed :  Journals_Metadata


677it [12:42,  1.01it/s]

Directory already existed :  Journals_Metadata


679it [12:44,  1.15it/s]

Directory already existed :  Journals_Metadata


680it [12:45,  1.12it/s]

Directory already existed :  Journals_Metadata


681it [12:46,  1.11it/s]

Directory already existed :  Journals_Metadata


682it [12:47,  1.14it/s]

Directory already existed :  Journals_Metadata


683it [12:48,  1.17it/s]

Directory already existed :  Journals_Metadata


684it [12:49,  1.08it/s]

Directory already existed :  Journals_Metadata


685it [12:50,  1.03it/s]

Directory already existed :  Journals_Metadata


686it [12:51,  1.02it/s]

Directory already existed :  Journals_Metadata


687it [12:52,  1.00it/s]

Directory already existed :  Journals_Metadata


688it [12:53,  1.07it/s]

Directory already existed :  Journals_Metadata


689it [12:53,  1.09it/s]

Directory already existed :  Journals_Metadata


690it [12:54,  1.05it/s]

Directory already existed :  Journals_Metadata


691it [12:55,  1.13it/s]

Directory already existed :  Journals_Metadata


692it [12:56,  1.05it/s]

Directory already existed :  Journals_Metadata


693it [12:57,  1.00it/s]

Directory already existed :  Journals_Metadata


694it [12:58,  1.02it/s]

Directory already existed :  Journals_Metadata


695it [13:00,  1.06s/it]

Directory already existed :  Journals_Metadata


696it [13:01,  1.03s/it]

Directory already existed :  Journals_Metadata


697it [13:01,  1.01s/it]

Directory already existed :  Journals_Metadata


698it [13:02,  1.04it/s]

Directory already existed :  Journals_Metadata


699it [13:03,  1.05it/s]

Directory already existed :  Journals_Metadata


700it [13:04,  1.11it/s]

Directory already existed :  Journals_Metadata


701it [13:05,  1.09it/s]

Directory already existed :  Journals_Metadata


702it [13:06,  1.04it/s]

Directory already existed :  Journals_Metadata


703it [13:07,  1.01it/s]

Directory already existed :  Journals_Metadata


704it [13:08,  1.00it/s]

Directory already existed :  Journals_Metadata


705it [13:09,  1.00s/it]

Directory already existed :  Journals_Metadata


706it [13:10,  1.01s/it]

Directory already existed :  Journals_Metadata


707it [13:11,  1.01it/s]

Directory already existed :  Journals_Metadata


708it [13:12,  1.02it/s]

Directory already existed :  Journals_Metadata


709it [13:13,  1.01s/it]

Directory already existed :  Journals_Metadata


710it [13:14,  1.03s/it]

Directory already existed :  Journals_Metadata


711it [13:15,  1.02s/it]

Directory already existed :  Journals_Metadata


712it [13:16,  1.03it/s]

Directory already existed :  Journals_Metadata


713it [13:17,  1.06it/s]

Directory already existed :  Journals_Metadata


714it [13:18,  1.10it/s]

Directory already existed :  Journals_Metadata


715it [13:19,  1.12it/s]

Directory already existed :  Journals_Metadata


716it [13:20,  1.10it/s]

Directory already existed :  Journals_Metadata


717it [13:21,  1.09it/s]

Directory already existed :  Journals_Metadata


718it [13:22,  1.07s/it]

Directory already existed :  Journals_Metadata


719it [13:28,  2.52s/it]

Directory already existed :  Journals_Metadata


720it [13:29,  2.05s/it]

Directory already existed :  Journals_Metadata


721it [13:30,  1.67s/it]

Directory already existed :  Journals_Metadata


722it [13:31,  1.49s/it]

Directory already existed :  Journals_Metadata


723it [13:32,  1.41s/it]

Directory already existed :  Journals_Metadata


724it [13:33,  1.32s/it]

Directory already existed :  Journals_Metadata


725it [13:34,  1.24s/it]

Directory already existed :  Journals_Metadata


726it [13:35,  1.15s/it]

Directory already existed :  Journals_Metadata


727it [13:36,  1.10s/it]

Directory already existed :  Journals_Metadata


728it [13:37,  1.02s/it]

Directory already existed :  Journals_Metadata


729it [13:38,  1.03s/it]

Directory already existed :  Journals_Metadata


730it [13:39,  1.01s/it]

Directory already existed :  Journals_Metadata


731it [13:40,  1.04it/s]

Directory already existed :  Journals_Metadata


732it [13:41,  1.06it/s]

Directory already existed :  Journals_Metadata


733it [13:42,  1.03it/s]

Directory already existed :  Journals_Metadata


735it [13:43,  1.09it/s]

Directory already existed :  Journals_Metadata


736it [13:44,  1.04it/s]

Directory already existed :  Journals_Metadata


737it [13:45,  1.04it/s]

Directory already existed :  Journals_Metadata


739it [13:47,  1.13it/s]

Directory already existed :  Journals_Metadata


740it [13:48,  1.20it/s]

Directory already existed :  Journals_Metadata


741it [13:49,  1.14it/s]

Directory already existed :  Journals_Metadata


742it [13:50,  1.06it/s]

Directory already existed :  Journals_Metadata


743it [13:51,  1.03it/s]

Directory already existed :  Journals_Metadata


744it [13:52,  1.01it/s]

Directory already existed :  Journals_Metadata


745it [13:53,  1.07it/s]

Directory already existed :  Journals_Metadata


746it [13:54,  1.04it/s]

Directory already existed :  Journals_Metadata


747it [13:55,  1.08it/s]

Directory already existed :  Journals_Metadata


748it [13:56,  1.00s/it]

Directory already existed :  Journals_Metadata


749it [13:57,  1.01it/s]

Directory already existed :  Journals_Metadata


750it [13:58,  1.06s/it]

Directory already existed :  Journals_Metadata


751it [14:07,  3.46s/it]

Directory already existed :  Journals_Metadata


752it [14:08,  2.74s/it]

Directory already existed :  Journals_Metadata


753it [14:09,  2.22s/it]

Directory already existed :  Journals_Metadata


754it [14:10,  1.85s/it]

Directory already existed :  Journals_Metadata


755it [14:11,  1.56s/it]

Directory already existed :  Journals_Metadata


756it [14:12,  1.39s/it]

Directory already existed :  Journals_Metadata


757it [14:13,  1.26s/it]

Directory already existed :  Journals_Metadata


758it [14:14,  1.17s/it]

Directory already existed :  Journals_Metadata


759it [14:15,  1.06s/it]

Directory already existed :  Journals_Metadata


760it [14:15,  1.01it/s]

Directory already existed :  Journals_Metadata


761it [14:16,  1.03it/s]

Directory already existed :  Journals_Metadata


762it [14:17,  1.06it/s]

Directory already existed :  Journals_Metadata


763it [14:18,  1.10it/s]

Directory already existed :  Journals_Metadata


764it [14:19,  1.05it/s]

Directory already existed :  Journals_Metadata


765it [14:20,  1.04it/s]

Directory already existed :  Journals_Metadata


766it [14:21,  1.06it/s]

Directory already existed :  Journals_Metadata


767it [14:22,  1.05it/s]

Directory already existed :  Journals_Metadata


768it [14:23,  1.08it/s]

Directory already existed :  Journals_Metadata


769it [14:29,  2.47s/it]

Directory already existed :  Journals_Metadata


770it [14:30,  2.00s/it]

Directory already existed :  Journals_Metadata


771it [14:31,  1.67s/it]

Directory already existed :  Journals_Metadata


772it [14:32,  1.42s/it]

Directory already existed :  Journals_Metadata


773it [14:33,  1.27s/it]

Directory already existed :  Journals_Metadata


774it [14:33,  1.16s/it]

Directory already existed :  Journals_Metadata


775it [14:35,  1.13s/it]

Directory already existed :  Journals_Metadata


776it [14:35,  1.06s/it]

Directory already existed :  Journals_Metadata


777it [14:36,  1.03s/it]

Directory already existed :  Journals_Metadata


778it [14:37,  1.01it/s]

Directory already existed :  Journals_Metadata


779it [14:38,  1.05it/s]

Directory already existed :  Journals_Metadata


781it [14:40,  1.19it/s]

Directory already existed :  Journals_Metadata


782it [14:41,  1.13it/s]

Directory already existed :  Journals_Metadata


783it [14:42,  1.10it/s]

Directory already existed :  Journals_Metadata


784it [14:42,  1.15it/s]

Directory already existed :  Journals_Metadata


785it [14:43,  1.13it/s]

Directory already existed :  Journals_Metadata


786it [14:44,  1.13it/s]

Directory already existed :  Journals_Metadata


787it [14:45,  1.11it/s]

Directory already existed :  Journals_Metadata


788it [14:46,  1.15it/s]

Directory already existed :  Journals_Metadata


789it [14:47,  1.17it/s]

Directory already existed :  Journals_Metadata


790it [14:48,  1.13it/s]

Directory already existed :  Journals_Metadata


791it [14:49,  1.15it/s]

Directory already existed :  Journals_Metadata


792it [14:49,  1.12it/s]

Directory already existed :  Journals_Metadata


793it [14:50,  1.07it/s]

Directory already existed :  Journals_Metadata


794it [14:51,  1.05it/s]

Directory already existed :  Journals_Metadata


795it [14:52,  1.04it/s]

Directory already existed :  Journals_Metadata


796it [14:53,  1.01it/s]

Directory already existed :  Journals_Metadata


797it [14:54,  1.04it/s]

Directory already existed :  Journals_Metadata


798it [14:55,  1.00s/it]

Directory already existed :  Journals_Metadata


799it [14:56,  1.03it/s]

Directory already existed :  Journals_Metadata


800it [14:58,  1.01s/it]

Directory already existed :  Journals_Metadata


801it [14:58,  1.01it/s]

Directory already existed :  Journals_Metadata


802it [14:59,  1.04it/s]

Directory already existed :  Journals_Metadata


803it [15:00,  1.02s/it]

Directory already existed :  Journals_Metadata


804it [15:01,  1.01s/it]

Directory already existed :  Journals_Metadata


805it [15:02,  1.01s/it]

Directory already existed :  Journals_Metadata


806it [15:03,  1.03it/s]

Directory already existed :  Journals_Metadata


807it [15:04,  1.07it/s]

Directory already existed :  Journals_Metadata


808it [15:05,  1.07it/s]

Directory already existed :  Journals_Metadata


809it [15:06,  1.08it/s]

Directory already existed :  Journals_Metadata


810it [15:07,  1.01s/it]

Directory already existed :  Journals_Metadata


811it [15:08,  1.05it/s]

Directory already existed :  Journals_Metadata


812it [15:09,  1.07it/s]

Directory already existed :  Journals_Metadata


813it [15:10,  1.12it/s]

Directory already existed :  Journals_Metadata


814it [15:11,  1.01it/s]

Directory already existed :  Journals_Metadata


815it [15:12,  1.02it/s]

Directory already existed :  Journals_Metadata


816it [15:13,  1.04it/s]

Directory already existed :  Journals_Metadata


817it [15:14,  1.08it/s]

Directory already existed :  Journals_Metadata


818it [15:15,  1.07it/s]

Directory already existed :  Journals_Metadata


819it [15:21,  2.47s/it]

Directory already existed :  Journals_Metadata


820it [15:22,  2.03s/it]

Directory already existed :  Journals_Metadata


821it [15:23,  1.73s/it]

Directory already existed :  Journals_Metadata


822it [15:24,  1.48s/it]

Directory already existed :  Journals_Metadata


823it [15:25,  1.30s/it]

Directory already existed :  Journals_Metadata


824it [15:26,  1.25s/it]

Directory already existed :  Journals_Metadata


825it [15:27,  1.17s/it]

Directory already existed :  Journals_Metadata


826it [15:28,  1.15s/it]

Directory already existed :  Journals_Metadata


827it [15:29,  1.06s/it]

Directory already existed :  Journals_Metadata


828it [15:29,  1.00s/it]

Directory already existed :  Journals_Metadata


829it [15:30,  1.06it/s]

Directory already existed :  Journals_Metadata


830it [15:31,  1.13it/s]

Directory already existed :  Journals_Metadata


831it [15:32,  1.09it/s]

Directory already existed :  Journals_Metadata


832it [15:33,  1.07it/s]

Directory already existed :  Journals_Metadata


833it [15:34,  1.03it/s]

Directory already existed :  Journals_Metadata


834it [15:35,  1.02it/s]

Directory already existed :  Journals_Metadata


835it [15:36,  1.05it/s]

Directory already existed :  Journals_Metadata


836it [15:37,  1.03s/it]

Directory already existed :  Journals_Metadata


837it [15:38,  1.07it/s]

Directory already existed :  Journals_Metadata


838it [15:39,  1.13it/s]

Directory already existed :  Journals_Metadata


839it [15:39,  1.16it/s]

Directory already existed :  Journals_Metadata


840it [15:40,  1.14it/s]

Directory already existed :  Journals_Metadata


841it [15:41,  1.21it/s]

Directory already existed :  Journals_Metadata


842it [15:42,  1.13it/s]

Directory already existed :  Journals_Metadata


843it [15:43,  1.13it/s]

Directory already existed :  Journals_Metadata


844it [15:44,  1.17it/s]

Directory already existed :  Journals_Metadata


845it [15:45,  1.12it/s]

Directory already existed :  Journals_Metadata


846it [15:46,  1.04it/s]

Directory already existed :  Journals_Metadata


847it [15:47,  1.11it/s]

Directory already existed :  Journals_Metadata


848it [15:48,  1.09it/s]

Directory already existed :  Journals_Metadata


849it [15:48,  1.14it/s]

Directory already existed :  Journals_Metadata


850it [15:49,  1.06it/s]

Directory already existed :  Journals_Metadata


851it [15:51,  1.02s/it]

Directory already existed :  Journals_Metadata


852it [15:52,  1.01s/it]

Directory already existed :  Journals_Metadata


853it [15:52,  1.06it/s]

Directory already existed :  Journals_Metadata


854it [15:53,  1.07it/s]

Directory already existed :  Journals_Metadata


855it [15:55,  1.01s/it]

Directory already existed :  Journals_Metadata


856it [15:56,  1.01s/it]

Directory already existed :  Journals_Metadata


857it [15:57,  1.04s/it]

Directory already existed :  Journals_Metadata


858it [15:57,  1.02it/s]

Directory already existed :  Journals_Metadata


859it [15:58,  1.03it/s]

Directory already existed :  Journals_Metadata


860it [16:00,  1.01s/it]

Directory already existed :  Journals_Metadata


861it [16:00,  1.02it/s]

Directory already existed :  Journals_Metadata


862it [16:01,  1.09it/s]

Directory already existed :  Journals_Metadata


863it [16:02,  1.12it/s]

Directory already existed :  Journals_Metadata


864it [16:03,  1.15it/s]

Directory already existed :  Journals_Metadata


865it [16:04,  1.11it/s]

Directory already existed :  Journals_Metadata


866it [16:05,  1.14it/s]

Directory already existed :  Journals_Metadata


867it [16:05,  1.17it/s]

Directory already existed :  Journals_Metadata


868it [16:06,  1.14it/s]

Directory already existed :  Journals_Metadata


869it [16:12,  2.37s/it]

Directory already existed :  Journals_Metadata


870it [16:13,  1.89s/it]

Directory already existed :  Journals_Metadata


871it [16:14,  1.62s/it]

Directory already existed :  Journals_Metadata


872it [16:15,  1.41s/it]

Directory already existed :  Journals_Metadata


873it [16:16,  1.25s/it]

Directory already existed :  Journals_Metadata


874it [16:17,  1.11s/it]

Directory already existed :  Journals_Metadata


875it [16:18,  1.07s/it]

Directory already existed :  Journals_Metadata


876it [16:19,  1.06s/it]

Directory already existed :  Journals_Metadata


877it [16:20,  1.03s/it]

Directory already existed :  Journals_Metadata


878it [16:21,  1.00s/it]

Directory already existed :  Journals_Metadata


879it [16:22,  1.03s/it]

Directory already existed :  Journals_Metadata


880it [16:22,  1.04it/s]

Directory already existed :  Journals_Metadata


881it [16:23,  1.10it/s]

Directory already existed :  Journals_Metadata


882it [16:24,  1.16it/s]

Directory already existed :  Journals_Metadata


883it [16:25,  1.10it/s]

Directory already existed :  Journals_Metadata


884it [16:26,  1.05it/s]

Directory already existed :  Journals_Metadata


885it [16:27,  1.01it/s]

Directory already existed :  Journals_Metadata


886it [16:28,  1.01it/s]

Directory already existed :  Journals_Metadata


887it [16:29,  1.00it/s]

Directory already existed :  Journals_Metadata


888it [16:30,  1.00s/it]

Directory already existed :  Journals_Metadata


889it [16:31,  1.09it/s]

Directory already existed :  Journals_Metadata


890it [16:32,  1.09it/s]

Directory already existed :  Journals_Metadata


891it [16:33,  1.08it/s]

Directory already existed :  Journals_Metadata


892it [16:34,  1.07it/s]

Directory already existed :  Journals_Metadata


893it [16:35,  1.01s/it]

Directory already existed :  Journals_Metadata


894it [16:36,  1.01it/s]

Directory already existed :  Journals_Metadata


895it [16:37,  1.01it/s]

Directory already existed :  Journals_Metadata


896it [16:38,  1.06it/s]

Directory already existed :  Journals_Metadata


897it [16:38,  1.11it/s]

Directory already existed :  Journals_Metadata


898it [16:39,  1.09it/s]

Directory already existed :  Journals_Metadata


899it [16:40,  1.06it/s]

Directory already existed :  Journals_Metadata


900it [16:41,  1.01it/s]

Directory already existed :  Journals_Metadata


901it [16:42,  1.07it/s]

Directory already existed :  Journals_Metadata


902it [16:43,  1.05it/s]

Directory already existed :  Journals_Metadata


903it [16:44,  1.04it/s]

Directory already existed :  Journals_Metadata


904it [16:45,  1.06it/s]

Directory already existed :  Journals_Metadata


905it [16:46,  1.03it/s]

Directory already existed :  Journals_Metadata


906it [16:47,  1.08it/s]

Directory already existed :  Journals_Metadata


907it [16:48,  1.02s/it]

Directory already existed :  Journals_Metadata


908it [16:49,  1.03it/s]

Directory already existed :  Journals_Metadata


909it [16:50,  1.02it/s]

Directory already existed :  Journals_Metadata


910it [16:51,  1.06it/s]

Directory already existed :  Journals_Metadata


911it [16:52,  1.00s/it]

Directory already existed :  Journals_Metadata


912it [16:53,  1.07it/s]

Directory already existed :  Journals_Metadata


913it [16:54,  1.05it/s]

Directory already existed :  Journals_Metadata


914it [16:55,  1.12it/s]

Directory already existed :  Journals_Metadata


915it [16:56,  1.12it/s]

Directory already existed :  Journals_Metadata


916it [16:56,  1.12it/s]

Directory already existed :  Journals_Metadata


917it [16:57,  1.09it/s]

Directory already existed :  Journals_Metadata


918it [16:58,  1.12it/s]

Directory already existed :  Journals_Metadata


919it [17:04,  2.39s/it]

Directory already existed :  Journals_Metadata


920it [17:05,  1.93s/it]

Directory already existed :  Journals_Metadata


921it [17:06,  1.59s/it]

Directory already existed :  Journals_Metadata


922it [17:07,  1.42s/it]

Directory already existed :  Journals_Metadata


923it [17:08,  1.28s/it]

Directory already existed :  Journals_Metadata


924it [17:09,  1.16s/it]

Directory already existed :  Journals_Metadata


925it [17:10,  1.14s/it]

Directory already existed :  Journals_Metadata


926it [17:11,  1.07s/it]

Directory already existed :  Journals_Metadata


927it [17:12,  1.02s/it]

Directory already existed :  Journals_Metadata


928it [17:12,  1.00s/it]

Directory already existed :  Journals_Metadata


929it [17:13,  1.07it/s]

Directory already existed :  Journals_Metadata


930it [17:14,  1.05it/s]

Directory already existed :  Journals_Metadata


931it [17:15,  1.07it/s]

Directory already existed :  Journals_Metadata


932it [17:16,  1.11it/s]

Directory already existed :  Journals_Metadata


933it [17:17,  1.05it/s]

Directory already existed :  Journals_Metadata


934it [17:18,  1.08it/s]

Directory already existed :  Journals_Metadata


935it [17:19,  1.09it/s]

Directory already existed :  Journals_Metadata


936it [17:20,  1.07it/s]

Directory already existed :  Journals_Metadata


937it [17:21,  1.12it/s]

Directory already existed :  Journals_Metadata


938it [17:21,  1.17it/s]

Directory already existed :  Journals_Metadata


939it [17:22,  1.14it/s]

Directory already existed :  Journals_Metadata


940it [17:23,  1.11it/s]

Directory already existed :  Journals_Metadata


941it [17:24,  1.10it/s]

Directory already existed :  Journals_Metadata


942it [17:25,  1.10it/s]

Directory already existed :  Journals_Metadata


943it [17:26,  1.00it/s]

Directory already existed :  Journals_Metadata


944it [17:27,  1.04s/it]

Directory already existed :  Journals_Metadata


945it [17:28,  1.03s/it]

Directory already existed :  Journals_Metadata


946it [17:29,  1.06it/s]

Directory already existed :  Journals_Metadata


947it [17:30,  1.01s/it]

Directory already existed :  Journals_Metadata


948it [17:32,  1.06s/it]

Directory already existed :  Journals_Metadata


949it [17:32,  1.02s/it]

Created Directory :  Journals_Metadata/Cailiao Gongcheng


950it [17:33,  1.02s/it]

Directory already existed :  Journals_Metadata


951it [17:34,  1.01s/it]

Directory already existed :  Journals_Metadata


952it [17:35,  1.01s/it]

Directory already existed :  Journals_Metadata


953it [17:36,  1.04it/s]

Directory already existed :  Journals_Metadata


954it [17:37,  1.06it/s]

Directory already existed :  Journals_Metadata


955it [17:38,  1.03it/s]

Directory already existed :  Journals_Metadata


956it [17:39,  1.07it/s]

Directory already existed :  Journals_Metadata


957it [17:40,  1.08it/s]

Directory already existed :  Journals_Metadata


958it [17:41,  1.10it/s]

Directory already existed :  Journals_Metadata


959it [17:42,  1.04it/s]

Directory already existed :  Journals_Metadata


961it [17:44,  1.04it/s]

Directory already existed :  Journals_Metadata


962it [17:45,  1.01it/s]

Directory already existed :  Journals_Metadata


963it [17:46,  1.03it/s]

Directory already existed :  Journals_Metadata


964it [17:47,  1.04it/s]

Directory already existed :  Journals_Metadata


965it [17:48,  1.03it/s]

Directory already existed :  Journals_Metadata


966it [17:49,  1.02it/s]

Directory already existed :  Journals_Metadata


967it [17:50,  1.02it/s]

Directory already existed :  Journals_Metadata


968it [17:51,  1.04s/it]

Directory already existed :  Journals_Metadata


969it [17:57,  2.46s/it]

Directory already existed :  Journals_Metadata


970it [17:58,  2.01s/it]

Directory already existed :  Journals_Metadata


971it [17:59,  1.75s/it]

Directory already existed :  Journals_Metadata


972it [18:00,  1.53s/it]

Directory already existed :  Journals_Metadata


973it [18:01,  1.37s/it]

Directory already existed :  Journals_Metadata


974it [18:02,  1.24s/it]

Directory already existed :  Journals_Metadata


975it [18:03,  1.16s/it]

Directory already existed :  Journals_Metadata


976it [18:04,  1.06s/it]

Directory already existed :  Journals_Metadata


977it [18:05,  1.06s/it]

Directory already existed :  Journals_Metadata


978it [18:06,  1.07s/it]

Directory already existed :  Journals_Metadata


979it [18:07,  1.11s/it]

Directory already existed :  Journals_Metadata


980it [18:08,  1.12s/it]

Directory already existed :  Journals_Metadata


981it [18:09,  1.14s/it]

Directory already existed :  Journals_Metadata


982it [18:10,  1.10s/it]

Directory already existed :  Journals_Metadata


983it [18:11,  1.05s/it]

Directory already existed :  Journals_Metadata


984it [18:12,  1.06s/it]

Directory already existed :  Journals_Metadata


985it [18:13,  1.02s/it]

Directory already existed :  Journals_Metadata


986it [18:14,  1.06s/it]

Directory already existed :  Journals_Metadata


987it [18:15,  1.00it/s]

Directory already existed :  Journals_Metadata


988it [18:16,  1.06s/it]

Directory already existed :  Journals_Metadata


990it [18:18,  1.07it/s]

Directory already existed :  Journals_Metadata


991it [18:19,  1.05it/s]

Directory already existed :  Journals_Metadata


992it [18:20,  1.03it/s]

Directory already existed :  Journals_Metadata


993it [18:21,  1.00it/s]

Directory already existed :  Journals_Metadata


994it [18:22,  1.02it/s]

Directory already existed :  Journals_Metadata


995it [18:23,  1.01it/s]

Directory already existed :  Journals_Metadata


996it [18:25,  1.13s/it]

Directory already existed :  Journals_Metadata


997it [18:26,  1.11s/it]

Directory already existed :  Journals_Metadata


998it [18:27,  1.11s/it]

Directory already existed :  Journals_Metadata


999it [18:28,  1.13s/it]

Directory already existed :  Journals_Metadata


1000it [18:29,  1.15s/it]

Directory already existed :  Journals_Metadata


1001it [18:30,  1.06s/it]

Directory already existed :  Journals_Metadata


1002it [18:31,  1.03s/it]

Directory already existed :  Journals_Metadata


1003it [18:32,  1.05s/it]

Directory already existed :  Journals_Metadata


1004it [18:33,  1.02s/it]

Directory already existed :  Journals_Metadata


1005it [18:34,  1.08s/it]

Directory already existed :  Journals_Metadata


1006it [18:35,  1.04s/it]

Directory already existed :  Journals_Metadata


1007it [18:36,  1.03it/s]

Directory already existed :  Journals_Metadata


1008it [18:37,  1.07s/it]

Directory already existed :  Journals_Metadata


1009it [18:38,  1.11s/it]

Directory already existed :  Journals_Metadata


1010it [18:40,  1.10s/it]

Directory already existed :  Journals_Metadata


1011it [18:41,  1.11s/it]

Directory already existed :  Journals_Metadata


1012it [18:42,  1.15s/it]

Directory already existed :  Journals_Metadata


1013it [18:43,  1.20s/it]

Directory already existed :  Journals_Metadata


1014it [18:44,  1.14s/it]

Directory already existed :  Journals_Metadata


1015it [18:45,  1.17s/it]

Directory already existed :  Journals_Metadata


1016it [18:47,  1.19s/it]

Directory already existed :  Journals_Metadata


1017it [18:48,  1.14s/it]

Directory already existed :  Journals_Metadata


1018it [18:49,  1.10s/it]

Directory already existed :  Journals_Metadata


1019it [18:55,  2.57s/it]

Directory already existed :  Journals_Metadata


1020it [18:56,  2.11s/it]

Directory already existed :  Journals_Metadata


1021it [18:57,  1.81s/it]

Directory already existed :  Journals_Metadata


1022it [18:58,  1.57s/it]

Directory already existed :  Journals_Metadata


1023it [18:59,  1.41s/it]

Directory already existed :  Journals_Metadata


1024it [19:00,  1.33s/it]

Directory already existed :  Journals_Metadata


1025it [19:01,  1.21s/it]

Directory already existed :  Journals_Metadata


1026it [19:02,  1.11s/it]

Directory already existed :  Journals_Metadata


1027it [19:03,  1.04s/it]

Directory already existed :  Journals_Metadata


1028it [19:04,  1.07s/it]

Directory already existed :  Journals_Metadata


1030it [19:06,  1.03it/s]

Directory already existed :  Journals_Metadata


1031it [19:07,  1.05it/s]

Directory already existed :  Journals_Metadata


1032it [19:07,  1.12it/s]

Directory already existed :  Journals_Metadata


1033it [19:08,  1.12it/s]

Directory already existed :  Journals_Metadata


1034it [19:09,  1.05it/s]

Directory already existed :  Journals_Metadata


1035it [19:10,  1.04it/s]

Directory already existed :  Journals_Metadata


1036it [19:11,  1.01it/s]

Directory already existed :  Journals_Metadata


1037it [19:12,  1.01s/it]

Directory already existed :  Journals_Metadata


1038it [19:13,  1.01it/s]

Directory already existed :  Journals_Metadata


1039it [19:14,  1.01s/it]

Directory already existed :  Journals_Metadata


1040it [19:15,  1.04it/s]

Directory already existed :  Journals_Metadata


1041it [19:16,  1.01s/it]

Directory already existed :  Journals_Metadata


1042it [19:17,  1.01it/s]

Directory already existed :  Journals_Metadata


1043it [19:18,  1.00it/s]

Directory already existed :  Journals_Metadata


1044it [19:19,  1.06it/s]

Directory already existed :  Journals_Metadata


1045it [19:20,  1.08it/s]

Directory already existed :  Journals_Metadata


1046it [19:21,  1.03it/s]

Directory already existed :  Journals_Metadata


1047it [19:22,  1.09it/s]

Directory already existed :  Journals_Metadata


1048it [19:23,  1.01s/it]

Directory already existed :  Journals_Metadata


1049it [19:24,  1.00s/it]

Directory already existed :  Journals_Metadata


1050it [19:25,  1.02s/it]

Directory already existed :  Journals_Metadata


1051it [19:27,  1.14s/it]

Directory already existed :  Journals_Metadata


1052it [19:28,  1.10s/it]

Created Directory :  Journals_Metadata/MMWR. Surveillance summaries : Morbidity and mortality weekly report. Surveillance summaries 


1053it [19:29,  1.08s/it]

Directory already existed :  Journals_Metadata


1054it [19:29,  1.01s/it]

Directory already existed :  Journals_Metadata


1055it [19:30,  1.02s/it]

Directory already existed :  Journals_Metadata


1056it [19:31,  1.01it/s]

Directory already existed :  Journals_Metadata


1058it [19:34,  1.04s/it]

Directory already existed :  Journals_Metadata


1059it [19:35,  1.00s/it]

Directory already existed :  Journals_Metadata


1060it [19:36,  1.00it/s]

Directory already existed :  Journals_Metadata


1062it [19:37,  1.12it/s]

Directory already existed :  Journals_Metadata/MMWR. Surveillance summaries : Morbidity and mortality weekly report. Surveillance summaries 


1067it [19:42,  1.00s/it]

Directory already existed :  Journals_Metadata


1069it [19:49,  2.47s/it]

Directory already existed :  Journals_Metadata


1070it [19:50,  1.11s/it]


In [35]:
"""1071 iters"""
AllJournalNames = big_df["JournalName"]
ImpactFactor2020 = big_df["ImpactFactor2020"]
Sources = big_df["Source"]
Types = big_df["Type"]

In [36]:
big_df.to_csv("OpenAccessJournalsDataRaw.csv",index=False)

In [38]:
big_df.to_excel("OpenAccessJournalsDataRaw.xlsx",index=False)

In [37]:
main_df = pd.DataFrame.from_dict({"JournalName" : AllJournalNames,
                            "ImpactFactor2020" : ImpactFactor2020 ,
                            "Source" : Sources,
                            "Type" : Types,
                            "Title" : Title,
                            "Publisher":Publisher,
                            "ISSN":ISSN,
                            "DoIsbyYear":DoIsbyYear,
                            "BackFileDoIs":BackFileDoIs ,
                            "CurrentDoIs":CurrentDoIs,
                            "TotalDoIs":TotalDoIs,
                            "Subjects":Subjects,
                            "ImpactFactor":IF,
                            "Journals_Metadata_Paths":Journals_Metadata_Paths
                            })
main_df.to_csv("MainOpenAccessJournalsData.csv",index=False)

In [39]:
main_df.to_excel("MainOpenAccessJournalsData.xlsx",index=False)